development:
  adapter: postgresql
  host: localhost
  database: webstate_dev
  username: postgres
  password: postgres
  pool: 40
  timeout: 5000

staging:
  adapter: postgresql
  host: localhost
  database: webstate_dev
  username: postgres
  password: postgres
  pool: 40
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: webstate_dev
  username: postgres
  password: postgres
  pool: 40
  timeout: 5000